backend:
  name: github
  repo: P4pratham/P4pratham.github.io
  branch: main

media_folder: "liquid/assets/blogs"
public_folder: "../assets/blogs"

display_url: https://p4pratham.github.io

collections:
  - name: "blogs"
    label: "Blog Posts"
    folder: "liquid/blogs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Read Time", name: "readTime", widget: "string", default: "5 min read" }
      - { label: "Cover Image", name: "coverImage", widget: "image", required: false }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list", default: ["Data Engineering", "Azure"] }
      - { label: "Body Content (HTML / Text)", name: "content", widget: "markdown" }
